export const SET_CURRENT_USER = 'SET_CURRENT_USER'

export const LOGIN_SMS_CODE_SUCCESS = 'LOGIN_SMS_CODE_SUCCESS';
export const LOGIN_SMS_CODE_ERROR = 'LOGIN_SMS_CODE_ERROR';
export const LOGIN_THROUGH_SMSCODE_SUCCESS = 'LOGIN_THROUGH_SMSCODE_SUCCESS';
export const LOGIN_THROUGH_SMSCODE_ERROR = 'LOGIN_THROUGH_SMSCODE_ERROR';
export const LOGIN_THROUGH_USERNAME_PASS_SUCCESS = 'LOGIN_THROUGH_USERNAME_PASS_SUCCESS';
export const LOGIN_THROUGH_USERNAME_PASS_ERROR = 'LOGIN_THROUGH_USERNAME_PASS_ERROR';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';
export const GET_CURRENT_USER_ERROR = 'GET_CURRENT_USER_ERROR';
export const SET_CURRENT_USER_DETAIL = 'SET_CURRENT_USER_DETAIL';
export const STORE_GET_CURRENT_USER = 'STORE_GET_CURRENT_USER';

export const REGISTER_SMS_CODE_SUCCESS = 'REGISTER_SMS_CODE_SUCCESS';
export const REGISTER_SMS_CODE_ERROR = 'REGISTER_SMS_CODE_ERROR';
export const REGISTER_NEW_ORG_AND_VENUE_SUCCESS = 'REGISTER_NEW_ORG_AND_VENUE_SUCCESS';
export const REGISTER_NEW_ORG_AND_VENUE_ERROR = 'REGISTER_NEW_ORG_AND_VENUE_ERROR';

export const CLASS_TEMPLATE_LIST_SUCCESS = 'CLASS_TEMPLATE_LIST_SUCCESS';
export const CLASS_TEMPLATE_LIST_ERROR = 'CLASS_TEMPLATE_LIST_ERROR';

export const SET_VENUE_ID = 'SET_VENUE_ID';
export const LIST_VENUES_SUCCESS = 'LIST_VENUES_SUCCESS';
export const LIST_VENUES_ERROR = 'LIST_VENUES_ERROR';
export const VENUE_BY_ID_SUCCESS = 'VENUE_BY_ID_SUCCESS';
export const VENUE_BY_ID_ERROR = 'VENUE_BY_ID_ERROR';
export const VENUE_STATS_SUCCESS = 'VENUE_STATS_SUCCESS';
export const VENUE_STATS_ERROR = 'VENUE_STATS_ERROR';

export const CLASS_LIST_SUCCESS = 'CLASS_LIST_SUCCESS';
export const CLASS_LIST_ERROR = 'CLASS_LIST_ERROR';
export const CLASS_PT_SESSIONS_SUCCESS = 'CLASS_PT_SESSIONS_SUCCESS';
export const CLASS_PT_SESSIONS_ERROR = 'CLASS_PT_SESSIONS_ERROR';

export const COLLABORATOR_LIST_SUCCESS = 'COLLABORATOR_LIST_SUCCESS';
export const COLLABORATOR_LIST_ERROR = 'COLLABORATOR_LIST_ERROR';

export const CLASS_PACKAGE_LIST_SUCCESS = 'CLASS_PACKAGE_LIST_SUCCESS';
export const CLASS_PACKAGE_LIST_ERROR = 'CLASS_PACKAGE_LIST_ERROR';
